### ISSUE TITLE
trigger on cloud (bewolking) change not working

### ISSUE THREAD

**Issue by marcschut002** [jjtbsomhorst/eu.jeroensomhorst.darkskyweather#1]
I have made a trigger for 'bewolking is veranderd', but this doesn't do anything.
Could you please take a look at this?

**Comment by jjtbsomhorst** [comment]
@marcschut002  I just updated the github with a fix for this. Can you test using cli or not?

**Comment by marcschut002** [comment]
I will try using cli and get back to you, thanks

**Comment by marcschut002** [comment]
It looks like it's working now (beta branch). After switching the location back and forth the cloud coverage changed and triggered the right flow.

**Comment by jjtbsomhorst** [comment]
Ill gonna update the app on the store. Thanks for the quick testing
