### ISSUE TITLE
Cannot get 'current weather' to work. 

### ISSUE THREAD

**Issue by Patrick1610** [jjtbsomhorst/eu.jeroensomhorst.darkskyweather#2]
Hi, 

I have just installed the app and signed up on Dark Sky. 
Two things I can't figure out, hoping you can help me! 

The first is that the coordinates in my API are from Alcatraz. Since I (luckily) am not living on Alcatraz, I would like to change that, but I cannot seem to edit the API line in my Console. 

The second: When I copy/paste my API in the Homey 'current weather' app (tried with coordinates in the link and without) and add the same coordinates as in the longitude/latitude, the app does not receive any information. Whenever I edit the settings I get an error (settings_rejected). 

How can I get this to work properly? 

Thanks in advance! 

Patrick

**Comment by jjtbsomhorst** [comment]
I don't know what you are trying to do with the api link etc? The things you need are: 

1) The Longitude of the location you want to use
2) The Latitude of the location you want to use
3) A valid Api key

![image](https://user-images.githubusercontent.com/583355/53679469-4d0a6580-3ccd-11e9-91d2-0aeb7decb355.png)


When adding a device you need to fill in these three things. If you want to change the settings tap the device and hold to get all the info. Tick the cog and change the settings at advanced settings. Be sure to save.

**Comment by Patrick1610** [comment]
Ah, didn’t try to only use the api, but used the whole link (which I now think is an example). It works now, thanks a lot!!
