### ISSUE TITLE
Feature request: Condition cards

### ISSUE THREAD

**Issue by Patrick1610** [jjtbsomhorst/eu.jeroensomhorst.darkskyweather#3]
I was wondering if you are planning to implement ‘condition-cards’? I would, for example, like to trigger a specific scene with more lights on when I come home and it is really cloudy, using a condition card for cloudiness.

**Comment by jjtbsomhorst** [comment]
I just updated the beta branch. This should implement this change. If you know how to can use run the app using CLI and test it out?

**Comment by Patrick1610** [comment]
Wow, that’s really fast! I’m okay with running a beta app, but I don’t know how to run the app with CLI. Any simple instructions possible for that?

**Comment by jjtbsomhorst** [comment]
https://developer.athom.com/docs/apps/tutorial-Getting%20Started.html from point 5. First you need to download the beta branch.

**Comment by Patrick1610** [comment]
I really don't understand how I can use this to run an app on my current Homey..

**Comment by Patrick1610** [comment]
Can't I just install a beta through the Athom App Store?

**Comment by jjtbsomhorst** [comment]
You can but you need to wait until athom approves

**Comment by jjtbsomhorst** [comment]
beta branch has been updated on the app store.

**Comment by Patrick1610** [comment]
I got it! Updated and see the cards ;) Will be playing with those soon 🙃🎉 thanks!!
