### ISSUE TITLE
windSpeed and windGust is in Meters per second, displayed as km/h

### ISSUE THREAD

**Issue by marcschut002** [jjtbsomhorst/eu.jeroensomhorst.darkskyweather#6]
Hi @jjtbsomhorst,
With the hard winds this week I was curious what the metrics from darksky would say.
This is when I found out that the information from darksky is displayed incorrectly in Homey. (a bit to low). When I called the API directly I saw that the unit from darksky for windspeed and windgust are in Meter per second and not in km/h. I didn't check your code, but I don't think the values are calculated correctly?

**Comment by jjtbsomhorst** [comment]
Your right. This is a bug from my side. I will fix it in the next release.

**Comment by marcschut002** [comment]
thanks!
