### ISSUE TITLE
Foutieve meetwaarden

### ISSUE THREAD

**Issue by keeshelpt** [jjtbsomhorst/eu.jeroensomhorst.darkskyweather#8]
Ik gebruik Darksky in Homey.  Dit werkt prima maar ik heb wel het probleem dat de meetwaarden erg veel afwijken. Momenteel o.a. een temp van 29,27grC terwijl het buiten 14grC is. De longtitude en Latitude kloppen als ik deze check met Google Maps.
Help!

**Comment by jjtbsomhorst** [comment]
Ik zou zeggen. Draai de lat/long eens om..

**Comment by keeshelpt** [comment]
Briljant.
Opgelost
tnx voor de tip.

gr.
Kees

Op do 4 apr. 2019 om 18:59 schreef JJTB Somhorst <notifications@github.com>:
